sudo: required
services:
  - docker

before_install:
  - docker build -t tanuj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tanuj/react-test npm test

after_success:
  - docker build -t tanuj/nulti-client ./client
  - docker build -t tanuj/multi-nginx ./nginx
  - docker build -t tanuj/multi-server ./server
  - docker build -t tanuj/milit-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tanuj/nulti-client
  - docker push tanuj/multi-nginx
  - docker push tanuj/multi-server
  - docker push tanuj/milit-worker

