name: Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      docker:

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test React client
      run: docker build -t tanuj/react-test -f ./client/Dockerfile.dev ./client
          
    - name: Run tests on React client
      run: docker run tanuj/react-test npm test -- --coverage

    - name: Build Docker images
      run: |
        docker build -t tanuj/multi-client ./client
        docker build -t tanuj/multi-nginx ./nginx
        docker build -t tanuj/multi-server ./server
        docker build -t tanuj/multi-worker ./worker
